#ifndef _UXR_CLIENT_CONFIG_H_
#define _UXR_CLIENT_CONFIG_H_

#include <zephyr/toolchain.h>

#define UCLIENT_PLATFORM_ZEPHYR

#ifdef CONFIG_ROS2_MICROXRCEDDS_CLIENT_PROFILE_DISCOVERY
#define UCLIENT_PROFILE_DISCOVERY
#endif

#ifdef CONFIG_ROS2_MICROXRCEDDS_CLIENT_PROFILE_UDP
#define UCLIENT_PROFILE_UDP
#define UXR_CONFIG_UDP_TRANSPORT_MTU                  CONFIG_ROS2_MICROXRCEDDS_CLIENT_UDP_TRANSPORT_MTU
#endif

#ifdef CONFIG_ROS2_MICROXRCEDDS_CLIENT_PROFILE_TCP
#define UCLIENT_PROFILE_TCP
#define UXR_CONFIG_TCP_TRANSPORT_MTU                  CONFIG_ROS2_MICROXRCEDDS_CLIENT_TCP_TRANSPORT_MTU
#endif

#ifdef CONFIG_ROS2_MICROXRCEDDS_CLIENT_PROFILE_CAN
#define UCLIENT_PROFILE_CAN
#endif

#ifdef CONFIG_ROS2_MICROXRCEDDS_CLIENT_PROFILE_SERIAL
#define UCLIENT_PROFILE_SERIAL
#define UXR_CONFIG_SERIAL_TRANSPORT_MTU               CONFIG_ROS2_MICROXRCEDDS_CLIENT_SERIAL_TRANSPORT_MTU
#endif

#ifdef CONFIG_ROS2_MICROXRCEDDS_CLIENT_PROFILE_CUSTOM_TRANSPORT
#define UCLIENT_PROFILE_CUSTOM_TRANSPORT
#define UXR_CONFIG_CUSTOM_TRANSPORT_MTU               CONFIG_ROS2_MICROXRCEDDS_CLIENT_CUSTOM_TRANSPORT_MTU
#endif

#define UXR_CONFIG_MAX_OUTPUT_BEST_EFFORT_STREAMS     CONFIG_ROS2_MICROXRCEDDS_CLIENT_MAX_OUTPUT_BEST_EFFORT_STREAMS
#define UXR_CONFIG_MAX_OUTPUT_RELIABLE_STREAMS        CONFIG_ROS2_MICROXRCEDDS_CLIENT_MAX_OUTPUT_RELIABLE_STREAMS
#define UXR_CONFIG_MAX_INPUT_BEST_EFFORT_STREAMS      CONFIG_ROS2_MICROXRCEDDS_CLIENT_MAX_INPUT_BEST_EFFORT_STREAMS
#define UXR_CONFIG_MAX_INPUT_RELIABLE_STREAMS         CONFIG_ROS2_MICROXRCEDDS_CLIENT_MAX_INPUT_RELIABLE_STREAMS

#define UXR_CONFIG_MAX_SESSION_CONNECTION_ATTEMPTS    CONFIG_ROS2_MICROXRCEDDS_CLIENT_MAX_SESSION_CONNECTION_ATTEMPTS
#define UXR_CONFIG_MIN_SESSION_CONNECTION_INTERVAL    CONFIG_ROS2_MICROXRCEDDS_CLIENT_MIN_SESSION_CONNECTION_INTERVAL
#define UXR_CONFIG_MIN_HEARTBEAT_TIME_INTERVAL        CONFIG_ROS2_MICROXRCEDDS_CLIENT_MIN_HEARTBEAT_TIME_INTERVAL

#ifdef CONFIG_ROS2_MICROXRCEDDS_CLIENT_TWEAK_XRCE_WRITE_LIMIT
#define UCLIENT_TWEAK_XRCE_WRITE_LIMIT
#endif

#ifdef CONFIG_ROS2_MICROXRCEDDS_CLIENT_HARD_LIVELINESS_CHECK
#define UCLIENT_HARD_LIVELINESS_CHECK
#define UXR_CONFIG_HARD_LIVELINESS_CHECK_TIMEOUT_STR  STRINGIFY(CONFIG_ROS2_MICROXRCEDDS_CLIENT_HARD_LIVELINESS_CHECK_TIMEOUT)
#endif

#endif /* _UXR_CLIENT_CONFIG_H_ */
